# Workflow: Build & Deploy ASP.NET Core app to Azure Web App (SCPostal)

name: Build and deploy ASP.NET Core app to Azure Web App - SCPostal

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_277B9D3BBC05485EB272ADFD3E71A21B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1FB00DF716454D75BE3C676368DD3E3A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9420153CCE3B4F31A00F767EE98013F0 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'scpostal-hbbvg7e2cdhrcqbv'   # <--- nombre real
          package: .
